"""imports scripts from examples dir"""
from . import update_job_schedule  # noqa: F401
from . import create_sql_job  # noqa: F401
from . import create_bulk_job  # noqa: F401
from . import get_metrics  # noqa: F401
from . import delete_webhook  # noqa: F401
from . import create_jobs_from_template  # noqa: F401
from . import create_job  # noqa: F401
from . import delete_job  # noqa: F401
from . import get_about  # noqa: F401
from . import get_job_by_name  # noqa: F401
from . import get_conf_info  # noqa: F401
from . import test_examples  # noqa: F401
from . import start_job  # noqa: F401
from . import get_single_job_webhook_conf_info  # noqa: F401
from . import get_about_messages  # noqa: F401
from . import dbo_update_sql_job  # noqa: F401
from . import create_job_webhook  # noqa: F401
from . import get_webhooks  # noqa: F401
from . import get_tags  # noqa: F401
from . import create_tag  # noqa: F401
from . import create_credentials  # noqa: F401
from . import create_cmd_job  # noqa: F401
from . import update_pkg  # noqa: F401
from . import get_pkg  # noqa: F401
from . import update_job  # noqa: F401
from . import get_credentials  # noqa: F401
from . import get_single_job_status  # noqa: F401
from . import get_databases  # noqa: F401
from . import get_jobs  # noqa: F401
from . import get_single_job  # noqa: F401
from . import get_job_schedule  # noqa: F401
from . import update_job_credentials  # noqa: F401
